### PR TITLE
fix: resolve _extends in .github repo file

### LINKED ISSUE #166: getConfigFiles doesn't resolve _extends in .github repo file
**What happened?**

A file
* is located in the `.github` _repo_ and
* contains an `_extends` key.

Loading that file using `getConfigFiles(...)` will **not** resolve the `_extends` key.

**What did you expect to happen?**

Loading the file using `getConfigFiles(...)` will resolve the `_extends` key. That is what's happening if loading a file that is not located in the `.github` repo but a "normal" repo.
Actually what's really weird is loading a file that is in a "normal" repo and contains an `_extends` key that points to a file in a `.github` repo which again contains an `_extends` key, all files will correctly be resolved (!) So the bug only occurs if the _initial_ file loaded with `getConfigFiles` is located in the `.github` repo. If not the inital file but any subsequent file is located in the `.github` repo, everything works correctly.

**What the problem might be**

Looking at the [`getConfigFiles` implementation](https://github.com/probot/octokit-plugin-config/blob/02e81228f96cd277fa03f54516be32bff38e6d0e/src/util/get-config-files.ts#L24-L101), the bug is obvious:
https://github.com/probot/octokit-plugin-config/blob/02e81228f96cd277fa03f54516be32bff38e6d0e/src/util/get-config-files.ts#L37-L49

If the file that should be loaded can't be found in the "normal" repo (`if (!requestedRepoFile.config)`) the method tries to load the file from the `.github` repo (`const defaultRepoConfig = ...`). That's it, nothing more happens, the files are already returned :cry: What's missing before the `return` statement is the logic to resolve and `_extends` key, like it is done after the code snippet I posted (starting at line 51).

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #166

If this pull request get merged I would highly appreciate a new release :wink:

### CODE REVIEW

File: src/util/get-config-files.ts [hunk 1]
```diff
@@ -32,11 +32,13 @@ export async function getConfigFiles(
     ref: branch,
   });
 
+  const files = [requestedRepoFile];
```
Comment (mkurz) [inline src/util/get-config-files.ts:35]: I am just moving that `files` array up a bit and also already push files into it. Easy.

File: src/util/get-config-files.ts [hunk 2]
```diff
@@ -45,26 +47,25 @@ export async function getConfigFiles(
       path,
     });
 
-    return [requestedRepoFile, defaultRepoConfig];
+    files.push(defaultRepoConfig);
```
Comment (mkurz) [inline src/util/get-config-files.ts:50]: Instead of returning I just push the file from the `.github` repo in the `files` array so it will become part of the resolve chain.

File: src/util/get-config-files.ts [hunk 3]
```diff
@@ -45,26 +47,25 @@ export async function getConfigFiles(
...
   }
 
   // if the configuration has no `_extends` key, we are done here.
-  if (!requestedRepoFile.config._extends) {
-    return [requestedRepoFile];
+  if (!files[files.length - 1].config || !files[files.length - 1].config._extends) {
```
Comment (jetersen) [inline src/util/get-config-files.ts:54]: This would not work. Now `.github` entry is the last entry and the `requestedRepoFile` entry is never resolved

**Comment by jetersen** [comment]
The logic is somewhat flawed 😓

I am sure it is possible to rewrite it to simply loop over each next config object until no more _extends exist. Sounds like a enumerator with `moveNext` 😅

File: src/util/get-config-files.ts (hunk 3 above)
Comment (mkurz) [reply src/util/get-config-files.ts:54]: This does work. Please think about it again. **If** there is a `.github` entry, then yes, it is the last entry, and yes the `requestedRepoFile` (which is the first entry) will not be resolved  **in this case because it does exist anyway**. The `.github` entry will only be added and resolved when the `requestedRepoFile` does not exist, so there is no need to resolve the first entry in that case.
So I am 99,99% sure this is correct (never say 100 ;)

**Comment by mkurz** [comment]
> The logic is somewhat flawed

To be honest I don't think the logic is flawed.

> order also matters, requestedRepoFile should always be the first entry.

Order is correct. `requestedRepoFile` will always be first, the array `push(...)` method always appends at the end. So this is correct.

File: src/util/get-config-files.ts (hunk 3 above)
Comment (jetersen) [reply src/util/get-config-files.ts:54]: This wont be correct if both `.github` and `requestedRepoFile` and both have `extends`

File: src/util/get-config-files.ts [hunk 4]
```diff
@@ -32,11 +32,13 @@ export async function getConfigFiles(
     ref: branch,
   });
 
+  const files = [requestedRepoFile];
+
   // if no configuration file present in selected repository,
   // try to load it from the `.github` repository
-  if (!requestedRepoFile.config) {
+  if (!files[files.length - 1].config) {
```
Comment (jetersen) [inline src/util/get-config-files.ts:39]: No need to change this line it is confusing to read.

File: src/util/get-config-files.ts (hunk 2 above)
Comment (jetersen) [inline src/util/get-config-files.ts:50]: instead of pushing to files.

Just change requestedRepoFile to defaultRepoConfig to simplify the logic.

I had a hard time understanding it because of repeated `files[files.length - 1]`

**Review by jetersen — COMMENTED** [review]
I see now but it is not easy to read when you use files length repeatably

File: src/util/get-config-files.ts (hunk 3 above)
Comment (jetersen) [reply src/util/get-config-files.ts:54]: Okay no reason to use the files.push when you can simply change requestedRepoFile to defaultRepoConfig. Changing only one line :)

File: src/util/get-config-files.ts [hunk 5]
```diff
@@ -45,26 +47,25 @@ export async function getConfigFiles(
       path,
     });
 
-    return [requestedRepoFile, defaultRepoConfig];
```
Comment (jetersen) [inline src/util/get-config-files.ts:48]: This used to return `[null, defaultConfig]`

So no reason to maintain the array on line 35: `const files = [requestedRepoFile];`

File: src/util/get-config-files.ts (hunk 4 above)
Comment (mkurz) [reply src/util/get-config-files.ts:39]: The reason why I changed it is to make clear that now the `files` array is the primary thing to work with.

File: src/util/get-config-files.ts (hunk 2 above)
Comment (mkurz) [reply src/util/get-config-files.ts:50]: Changing it like you suggest means we would loose `requestedRepoFile` and I don't think that's a good idea. Even though its config is `null` we should still keep returning it to the method's caller, like before. If someone relies on the fact to get all the files back that have been tried, that would break with your suggestion.

File: src/util/get-config-files.ts (hunk 5 above)
Comment (mkurz) [reply src/util/get-config-files.ts:48]: Please see my other comment, I don't think it's a good idea to just not return `requestedRepoFile` anymore.

File: src/util/get-config-files.ts (hunk 3 above)
Comment (mkurz) [reply src/util/get-config-files.ts:54]: > This wont be correct if both `.github` and `requestedRepoFile` and both have `extends` only `.github` would be extended.

It's impossible that both `.github` and `requestedRepoFile` both have `_extends`, only the last one in the array might have (even if it's just one element). So this is correct.

File: src/util/get-config-files.ts (hunk 4 above)
Comment (mkurz) [reply src/util/get-config-files.ts:39]: I am doing this to not mix variable anymore, so if someone comes with another code change above these lines here all it needs to be done is push to files, without the need of thinking about a second variable. I think it's cleaner.

**Comment by mkurz** [comment]
Let's see what @gr2m thinks.

**Comment by gr2m** [comment]
> Let's see what @gr2m thinks.

sorry @gr2m is very busy right now, this will require more time and attention that I currently have available. If the two of you agree, I'd be okay with merging it

Thanks a lot @jetersen for the reviews and comments

**Comment by mkurz** [comment]
@gr2m yes please merge. We were discussing code style, but the logic is correct.
Could you please also release a new version?
Thanks!

**Comment by mkurz** [comment]
@gr2m You need to also approve the workflows to run for that pull request.

**Comment by mkurz** [comment]
@gr2m Fixed the formatting, please approve again, thanks!

**Comment by mkurz** [comment]
Good morning @gr2m, can you please approve again? Thanks!

**Comment by mkurz** [comment]
@gr2m Again please, it should work now! I finally ran the checks locally. Thanks!

**Comment by mkurz** [comment]
OK, now this: "Jest: "global" coverage threshold for branches (100%) not met: 94.92%"...

**Comment by mkurz** [comment]
@gr2m Test coverage should be fixed now as well... Sorry

**Comment by mkurz** [comment]
@gr2m Hopefully just one last time approving... :heart:

File: src/util/get-config-files.ts [hunk 6]
```diff
@@ -45,26 +47,27 @@ export async function getConfigFiles(
...
+    files.push(defaultRepoConfig);
   }
 
+  const file = files[files.length - 1];
```
Comment (jetersen) [inline src/util/get-config-files.ts:53]: Much more readable!

**Review by jetersen — APPROVED** [review]

File: src/util/get-config-files.ts (hunk 6 above)
Comment (mkurz) [reply src/util/get-config-files.ts:53]: :+1:

File: src/util/get-config-files.ts [hunk 7]
```diff
@@ -45,26 +47,27 @@ export async function getConfigFiles(
...
+
   // if the configuration has no `_extends` key, we are done here.
-  if (!requestedRepoFile.config._extends) {
-    return [requestedRepoFile];
+  if (!file.config?._extends) {
```
Comment (gr2m) [inline src/util/get-config-files.ts:56]: this will break in Node 10 which the current version still supports

Comment (mkurz) [reply src/util/get-config-files.ts]: Replaced with `if (!file.config || !file.config._extends) {`, let's see now.

**Review by jetersen — DISMISSED** [review]

File: src/util/get-config-files.ts (hunk 7 above)
Comment (mkurz) [reply src/util/get-config-files.ts]: @gr2m This should be really it now... (I know I said that before) Approval needed....

**Review by gr2m — CHANGES_REQUESTED** [review]
can you please add a test? It would help a lot if you could push the test changes first, so we can see the CI fail, then push the implementation.

**Comment by mkurz** [comment]
@gr2m Alright, I now pushed a test which will fail. Holding back the fix and will commit after the test ran.

File: test/get.test.ts [hunk 8]
```diff
@@ -180,6 +180,48 @@ describe("octokit.config.get", () => {
...
+  it("resolves _extends in .github repository file", async () => {
+    const mock = fetchMock
+      .sandbox()
+      .getOnce(
+        "https://api.github.com/repos/octocat/hello-world/contents/.github%2Fmy-app.yml",
+        NOT_FOUND_RESPONSE
+      )
+      .getOnce(
+        "https://api.github.com/repos/octocat/.github/contents/.github%2Fmy-app.yml",
+        `_extends: '.github:.github/my-second-app.yml'`
```
Comment (mkurz) [inline test/get.test.ts:192]: This `_extends` will not be resolved, which is a bug.

**Comment by mkurz** [comment]
@gr2m Once more your approval is needed.

**Comment by mkurz** [comment]
@gr2m Because it's late here I will go to bed. However, I just entered this into my command line:
```
$ sleep 7200 ; git push
```
which means around 6:18 pm L.A. time the implementation will be pushed, so I hope you approved until then, so afterwards you could approve the implementation as well, merge and release...

I know, it's a though plan :stuck_out_tongue_winking_eye:

**Comment by mkurz** [comment]
The plan didn't work, so I removed that second commit again for now :wink:

**Comment by gr2m** [comment]
You can push the fix now

**Comment by mkurz** [comment]
Pushed

**Review by gr2m — APPROVED** [review]
thank you both 💐

**Comment by mkurz** [comment]
@gr2m Thank you! Can you release that fix?

**Comment by mkurz** [comment]
Thank you very much!
